<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link href="/css/style.css" media="all" rel="stylesheet" type="text/css" />


<script type="text/javascript">
    

    
    
	
</script>





</head>
<body>
<div id="pageWrapper">
<div id="header">
</div>


<div id="main">
<form id="btns"method="POST" action="/index/"> <b><center><p id="ph">Thank you Customer.Its our pleasure in Assist you</p></center> </b><br /><br />
    
 
        
        
   
    
    <br><br>
    <center>	<input id="bt" type="submit" value="Goodbye.!"s/> </center>
    <br>
     
</form>
   
</div>
<div id="footer">
<p><center>copyright::Practo.com</center></p>
</div>
</div>
</body>
</html>
