<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link href="/css/style.css" media="all" rel="stylesheet" type="text/css" />

<script type="text/javascript">
	/*
	function hi()
	{
		alert('i have called') 
	window.open("/usr");
	}
	
	
	*/
</script>


</head>
<body>
<div id="pageWrapper">
<div id="header">
</div>


<div id="main">
	<div id="btns"> 
<form id="bt1" method="POST" action="/user/user/"> <b><center>Greetings.! Welcome To Practo.com</center> </b><br /><br />
<center>	<input id="bt" value="I am a user" type="submit" /></center><br />
</form>
<form method="POST" action="/rep/rep/">
	<center><input id="bt" type="submit" value="I am a Rep" /></center> 
</form>
</div>
</div>
<div id="footer">
<p><center>copyright::Practo.com</center></p>
</div>
</div>
</body>
</html>
