<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link href="/css/style.css" media="all" rel="stylesheet" type="text/css" />

<script type="text/javascript">
	
	function hi()
	{
		
	alert('I am sorry, Man @ work!');
	}
	
	
	
</script>


</head>
<body>
<div id="pageWrapper">
<div id="header">
</div>


<div id="main">
    <div id="btns"> 
<form > <b><center>Welcome User</center> </b><br /><br />
<center>	<input id="bt" type="button" value="view Requests" type="submit"onclick="hi();"/></center><br />

</form>
<form method="POST" action="/happy/happy/">
<center><input id="bt" value="Today's H-index" type="submit"/></center>
	
</form>
</div>
</div>
<div id="footer">
<p><center>copyright::Practo.com</center></p>
</div>
</div>
</body>
</html>
