<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link href="/home/selvakumaran/LAPP/apache2/htdocs/PRACTO/public/css/style.css" media="all" rel="stylesheet" type="text/css" />

<script type="text/javascript">
	
	function hi()
	{
		
	alert('Welcome to practo');
	}
	
	
	
</script>


</head>
<body>
<div id="pageWrapper">
<div id="header">
</div>


<div id="main">
<form id="btns"> <b><center>Welcome Representative</center> </b><br /><br />
<center>	<input id="bt" type="button" value="view Requests" type="submit"onclick="hi();"/></center><br />
<center><input id="bt" type="button" value="Today's H-index" type="submit"/></center>
	
</form>
</div>
<div id="footer">
<p><center>copyright::Practo.com</center></p>
</div>
</div>
</body>
</html>
