<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <link href="/css/style.css" media="all" rel="stylesheet" type="text/css" />

        <script type="text/javascript">
	
            function hi()
            {
		
                alert('I am sorry, Man @ work!');
            }
	
	
	
        </script>


    </head>
    <body>
        <div id="pageWrapper">
            <div id="header">
            </div>


            <div id="main">
                <div id="btns"> 

                    <div id="happy"></div> 
                    <?php
                    $result = $this->result;
                   
                    //print_r($result);

                    ?>
                    <?php
                    // Standard inclusions     
                    include("pChart/pData.class");
                    include("pChart/pChart.class");

                    // Dataset definition   
                    $DataSet = new pData;
                    $DataSet->AddPoint(array(50, 50), "Serie1");
                    //$DataSet->AddPoint(array("Jan","Feb","Mar","Apr","May"),"Serie2");  
                    $DataSet->AddAllSeries();
                    $DataSet->SetAbsciseLabelSerie("Serie2");

                    // Initialise the graph  
                    $Test = new pChart(380, 200);
                    $Test->drawFilledRoundedRectangle(7, 7, 373, 193, 5, 240, 240, 240);
                    $Test->drawRoundedRectangle(5, 5, 375, 195, 5, 230, 230, 230);

                    // Draw the pie chart  
                    $Test->setFontProperties("Fonts/tahoma.ttf", 8);
                    $Test->drawPieGraph($DataSet->GetData(), $DataSet->GetDataDescription(), 150, 90, 110, PIE_PERCENTAGE, TRUE, 50, 20, 5);
                    $Test->drawPieLegend(310, 15, $DataSet->GetData(), $DataSet->GetDataDescription(), 250, 250, 250);

                    $Test->Render("image/happyindex.png");
                    ?>


                </div>

            </div>
        </div>
        <div id="footer">
            <p><center>copyright::Practo.com</center></p>
    </div>
</div>
</body>
</html>
