<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link href="/css/style.css" media="all" rel="stylesheet" type="text/css" />


<script type="text/javascript">
    function call()
    {
        alert("Thanks for your comments, We'll fix it soon")
    }

    
    
	
</script>





</head>
<body>
<div id="pageWrapper">
<div id="header">
</div>


<div id="main">
<form id="btns"method="POST" action="/index/"> <b><center><p id="ph">We are sorry for that, please let us know what goes wrong</p></center> </b><br /><br />
    
 
        
   <center> <textarea name="fbstory" name="comments" cols="40" rows="5" >
Enter your comments here...
</textarea><br> </center>
    
    <br><br>
    <center>	<input id="bt" type="submit" value="submit" onclick="call()"/> </center>
    <br>
     
</form>
   
</div>
<div id="footer">
<p><center>copyright::Practo.com</center></p>
</div>
</div>
</body>
</html>
